[package]
name = "pong"
version = "0.1.0"
authors = []
edition = "2018"

[features]
profiler = [
    "amethyst/profiler",
]
nightly = [
    "amethyst/nightly",
]
sdl_controller = [
    "amethyst/sdl_controller",
]
debug = []
trace = []

[dependencies]
amethyst = "0.10.0"